<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Smart Car Parking</title>
  <style>
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
      font-family: 'Segoe UI', sans-serif;
    }
    body {
      background: #1a063a;
      color: white;
      min-height: 100vh;
    }
    .main-container {
      width: 100%;
      max-width: 1200px;
      margin: 0 auto;
      padding: 0 20px;
    }
    .navbar {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 20px 0;
      margin-bottom: 40px;
    }
    .logo {
      color: #ff66c4;
      font-size: 1.8rem;
      font-weight: bold;
    }
    .right-nav {
      display: flex;
      align-items: center;
    }
    .sign-in {
      color: white;
      text-decoration: none;
      margin-right: 20px;
    }
    .search-icon {
      width: 30px;
      height: 30px;
      background-color: #7030a0;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
    }
    .hero {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 60px;
    }
    .hero-text {
      width: 40%;
    }
    .hero-text h1 {
      font-size: 3.5rem;
      margin-bottom: 20px;
    }
    .hero-text p {
      color: #cccccc;
      margin-bottom: 30px;
      line-height: 1.6;
    }
    .hero-image {
      width: 55%;
      position: relative;
    }
    .hero-buttons {
      display: flex;
      gap: 15px;
    }
    .hero-btn {
      padding: 12px 25px;
      border-radius: 25px;
      border: none;
      cursor: pointer;
      font-weight: bold;
      transition: transform 0.2s;
    }
    .hero-btn:hover {
      transform: translateY(-3px);
    }
    .primary-btn {
      background: linear-gradient(to right, #ff66c4, #ff66af);
      color: white;
    }
    .secondary-btn {
      background: rgba(255, 255, 255, 0.1);
      border: 1px solid #ff66c4;
      color: white;
    }
    .parking-container {
      background: rgba(112, 48, 160, 0.3);
      border-radius: 15px;
      padding: 30px;
      margin-top: 40px;
    }
    .section-header {
      font-size: 2rem;
      margin-bottom: 25px;
      text-align: center;
    }
    .stats-row {
      display: flex;
      justify-content: space-around;
      margin-bottom: 30px;
    }
    .stat-card {
      background: rgba(255, 255, 255, 0.1);
      border-radius: 12px;
      padding: 20px;
      text-align: center;
      width: 45%;
      backdrop-filter: blur(10px);
    }
    .available-card .stat-number {
      color: #64ffda;
    }
    .occupied-card .stat-number {
      color: #ff6b6b;
    }
    .stat-number {
      font-size: 2.5rem;
      font-weight: bold;
    }
    .stat-label {
      font-size: 1.1rem;
      margin-top: 5px;
    }
    .book-button {
      display: block;
      width: 100%;
      padding: 15px;
      background: linear-gradient(to right, #ff66c4, #ff66af);
      color: white;
      border: none;
      border-radius: 10px;
      font-size: 1.2rem;
      cursor: pointer;
      margin-bottom: 30px;
      transition: transform 0.3s;
    }
    .book-button:hover {
      transform: translateY(-3px);
    }
    .slots-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
      gap: 20px;
    }
    .slot {
      padding: 30px 15px;
      border-radius: 10px;
      color: white;
      text-align: center;
      font-weight: bold;
      cursor: pointer;
      transition: all 0.3s ease;
      position: relative;
      overflow: hidden;
    }
    .slot::before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: linear-gradient(45deg, rgba(255,255,255,0.1), rgba(255,255,255,0));
      z-index: 1;
    }
    .slot-text {
      font-size: 1.5rem;
      position: relative;
      z-index: 2;
    }
    .available-slot {
      background: linear-gradient(135deg, #36b37e, #2ecb88);
      box-shadow: 0 4px 15px rgba(54, 179, 126, 0.3);
    }
    .occupied-slot {
      background: linear-gradient(135deg, #e74c3c, #c0392b);
      box-shadow: 0 4px 15px rgba(231, 76, 60, 0.3);
      cursor: not-allowed;
    }
    .selected-slot {
      transform: translateY(-5px);
      box-shadow: 0 8px 25px rgba(255, 102, 196, 0.5);
      border: 2px solid #ff66c4;
    }
    .slot-status {
      font-size: 0.9rem;
      margin-top: 10px;
      position: relative;
      z-index: 2;
      letter-spacing: 1px;
    }
    .hour-options {
      display: flex;
      justify-content: space-between;
      margin: 20px 0;
      flex-wrap: wrap;
      gap: 10px;
    }
    .hour-option {
      background: linear-gradient(135deg, #ff66c4, #ff66af);
      border: none;
      color: white;
      font-size: 1.2rem;
      padding: 12px;
      border-radius: 10px;
      cursor: pointer;
      transition: transform 0.3s;
      width: 90px;
    }
    .hour-option:hover {
      transform: translateY(-5px);
    }
    .bill {
      background: rgba(255, 255, 255, 0.1);
      padding: 30px;
      border-radius: 10px;
      margin-top: 40px;
      color: #fff;
      box-shadow: 0 4px 20px rgba(255, 102, 196, 0.3);
    }
    .bill h3 {
      margin-bottom: 20px;
      text-align: center;
    }
    .bill-table {
      width: 100%;
      margin-top: 20px;
      border-collapse: collapse;
    }
    .bill-table th, .bill-table td {
      padding: 10px;
      border: 1px solid #ddd;
      text-align: center;
    }
    .bill-table th {
      background-color: #7030a0;
      color: white;
    }
  </style>
</head>
<body>
  <div class="main-container">
    <!-- Navigation -->
    <nav class="navbar">
      <div class="logo">SMART CAR PARKING</div>
      <div class="right-nav">
        <a href="#" class="sign-in">Sign In</a>
        <div class="search-icon">🔍</div>
      </div>
    </nav>

    <!-- Hero Section -->
    <section class="hero">
      <div class="hero-text">
        <h1>Smart Car Parking</h1>
        <p>No More “I’ll Just Wait for That Spot” Drama: Seriously, who has time for that? Let our system do the parking hustle while you chill.</p>
        <div class="hero-buttons">
          <button class="hero-btn primary-btn" onclick="showParkingArea()">Parking Area</button>
          <button class="hero-btn secondary-btn" onclick="showParkingSystem()">Booking</button>
        </div>
      </div>
      <div class="hero-image"></div>
    </section>

    <!-- Parking System UI -->
    <div class="parking-container" id="parkingSystem" style="display:none;">
      <h2 class="section-header">Smart Car Parking</h2>
      <div class="stats-row">
        <div class="stat-card available-card">
          <div class="stat-number" id="availableCount">7</div>
          <div class="stat-label">Available</div>
        </div>
        <div class="stat-card occupied-card">
          <div class="stat-number" id="occupiedCount">3</div>
          <div class="stat-label">Occupied</div>
        </div>
      </div>
      <div class="slots-grid">
        <div class="slot available-slot" id="SLOT1" onclick="selectSlot('SLOT1')">
          <div class="slot-text">SLOT 1</div>
          <div class="slot-status">AVAILABLE</div>
        </div>
        <div class="slot available-slot" id="SLOT2" onclick="selectSlot('SLOT2')">
          <div class="slot-text">SLOT 2</div>
          <div class="slot-status">AVAILABLE</div>
        </div>
        <div class="slot available-slot" id="SLOT3" onclick="selectSlot('SLOT3')">
          <div class="slot-text">SLOT 3</div>
          <div class="slot-status">AVAILABLE</div>
        </div>
        <div class="slot available-slot" id="SLOT4" onclick="selectSlot('SLOT4')">
          <div class="slot-text">SLOT 4</div>
          <div class="slot-status">AVAILABLE</div>
        </div>
        <div class="slot available-slot" id="SLOT5" onclick="selectSlot('SLOT5')">
          <div class="slot-text">SLOT 5</div>
          <div class="slot-status">AVAILABLE</div>
        </div>
        <div class="slot available-slot" id="SLOT6" onclick="selectSlot('SLOT6')">
          <div class="slot-text">SLOT 6</div>
          <div class="slot-status">AVAILABLE</div>
        </div>
        <div class="slot available-slot" id="SLOT7" onclick="selectSlot('SLOT7')">
          <div class="slot-text">SLOT 7</div>
          <div class="slot-status">AVAILABLE</div>
        </div>
        <div class="slot available-slot" id="SLOT8" onclick="selectSlot('SLOT8')">
          <div class="slot-text">SLOT 8</div>
          <div class="slot-status">AVAILABLE</div>
        </div>
        <div class="slot available-slot" id="SLOT9" onclick="selectSlot('SLOT9')">
          <div class="slot-text">SLOT 9</div>
          <div class="slot-status">AVAILABLE</div>
        </div>
        <div class="slot available-slot" id="SLOT10" onclick="selectSlot('SLOT10')">
          <div class="slot-text">SLOT 10</div>
          <div class="slot-status">AVAILABLE</div>
        </div>
      </div>
      <div class="hour-options" id="hourOptions" style="display:none;">
        <button class="hour-option" onclick="selectDuration(1)">1 Hour</button>
        <button class="hour-option" onclick="selectDuration(2)">2 Hours</button>
        <button class="hour-option" onclick="selectDuration(3)">3 Hours</button>
        <button class="hour-option" onclick="selectDuration(4)">4 Hours</button>
        <button class="hour-option" onclick="selectDuration(5)">5 Hours</button>
        <button class="hour-option" onclick="selectDuration(6)">6 Hours</button>
        <button class="hour-option" onclick="selectDuration(7)">7 Hours</button>
        <button class="hour-option" onclick="selectDuration(8)">8 Hours</button>
        <button class="hour-option" onclick="selectDuration(9)">9 Hours</button>
        <button class="hour-option" onclick="selectDuration(10)">10 Hours</button>
      </div>
    </div>

    <!-- Bill Section -->
    <div class="bill" id="bill" style="display:none;">
      <h3>Parking Bill</h3>
      <table class="bill-table">
        <tr>
          <th>IN Time</th>
          <th>OUT Time</th>
          <th>Duration</th>
          <th>Total Cost</th>
        </tr>
        <tr>
          <td id="inTime">-</td>
          <td id="outTime">-</td>
          <td id="duration">-</td>
          <td id="totalCost">-</td>
        </tr>
      </table>
    </div>
  </div>

  <script>
    let selectedSlot = null;
    const ratePerHour = 50;

    function showParkingSystem() {
      document.getElementById("parkingSystem").style.display = "block";
    }

    function selectSlot(slotId) {
      if (selectedSlot) {
        alert("You can only book one slot at a time.");
        return;
      }
      const slot = document.getElementById(slotId);
      if (slot.classList.contains("available-slot")) {
        slot.classList.add("selected-slot");
        slot.classList.remove("available-slot");
        selectedSlot = slotId;
        document.getElementById("hourOptions").style.display = "flex";
      }
    }

    function selectDuration(hours) {
      if (!selectedSlot) {
        alert("Please select a slot first.");
        return;
      }
      const now = new Date();
      const bookingTime = now;
      const outTime = new Date(now.getTime() + hours * 60 * 60 * 1000);
      const totalCost = ratePerHour * hours;

      document.getElementById("inTime").innerText = bookingTime.toLocaleString();
      document.getElementById("outTime").innerText = outTime.toLocaleString();
      document.getElementById("duration").innerText = hours + " Hour(s)";
      document.getElementById("totalCost").innerText = "₹ " + totalCost;

      document.getElementById("bill").style.display = "block";
      document.getElementById("hourOptions").style.display = "none";

      const slotElement = document.getElementById(selectedSlot);
      slotElement.classList.add("occupied-slot");
      slotElement.classList.remove("selected-slot");
      slotElement.querySelector(".slot-status").innerText = "OCCUPIED";
      slotElement.querySelector(".slot-status").style.color = "#fff";

      selectedSlot = null;
    }
  </script>
</body>
</html>
